### ISSUE TITLE
Combining processors

### ISSUE THREAD

**Issue by dy** [github/template-parts#41] opened 2022-01-06 16:42 UTC
I can see there's potential combining processors needed for `createCallback` as well.
Consider expression parsing processor and reactive processor. First parses parts expressions, second initializes observable state inputs.
```html
<div id="done">{{ done || '...' }}</div>

<script type="module">
  import Parts from 'github-template-parts.js'
  import { expression, reactive } from './processors.js'

  const done = new Promise(ok => setTimeout(() => ok('Done!'), 1000))

  const state = Parts(document.querySelector('#done'), { done }, [expression, reactive, propertyOrBoolean])
</script>
```
It would need a sequence of `createCallback`s, different from `processCallback`s.
(speaking of, #40 makes point here: would be more meaningful to separately call `processCallback` in constructor)

**Comment by keithamus** [comment] 2022-01-07 10:32
I concur this is a good use case justifying the existence of `createCallback` vs `processCallback`. 

This effectively feels like a dupe of #40 though. The actionable piece being: align closer to the spec. See #42. I'll close this and we can track in #40/#42

**Closed by keithamus** 2022-01-07 10:32 UTC
